### ISSUE TITLE
Create article controller

### ISSUE THREAD

**Issue by syawin** [syawin/newsboard#25]
# Tasks
- [ ] create article controller class
- [ ] add create article action.
- [ ] add list all articles action
- [ ] add list article by subject action
