### ISSUE TITLE
Create subject controller

### ISSUE THREAD

**Issue by syawin** [syawin/newsboard#26]
# Tasks
- [x] create subject controller class
- [x] add create subject action.
- [ ] add list all subjects action.
