### ISSUE TITLE
Create comment controller

### ISSUE THREAD

**Issue by syawin** [syawin/newsboard#27]
# Tasks
- [ ] Create comment controller class
- [ ] Add reply to article action.
- [ ] add reply to comment action.
- [ ] add list all comments action.
- [ ] add list comments by article action.
